version: '2'
services:
  postgres-db:
    image: postgres:9.6
    ports:
    - "54321:5432"
    environment:
      POSTGRES_DB: "world-test"
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
